os/board/rtl8730e To start softap on wlan1
a-jhanwar/TizenRT pull request #1
Opened 2024-08-14 08:19 UTC by Wuth5

2024-08-14 10:55 UTC, a-jhanwar requested changes
Please share your opinion on review comment.

2024-08-15 01:59 UTC, Wuth5 commented
hi abhishek,
yes you are correct, typo here, I will remove the debug log also
besides please also help to check if any flag was set incorrectly in [rtk_netmgr.c] also

2024-08-16 02:45 UTC, Wuth5 commented on os/board/rtl8730e/src/component/os/tizenrt/rtk_netmgr.c
> +	} else if(rtw_memcmp(dev->ifname,"wlan1",4)){
yes you are correct, typo here, I will fix it and besides will remove the debug log
please also help to check if any flag was set incorrectly in [rtk_netmgr.c]

2024-08-19 07:21 UTC, Wuth5 commented
hi abhishke, I have revised the code as per requested, kindly help to review again, thanks

2024-08-20 04:45 UTC, a-jhanwar approved these changes
Changes looks fine to me.

2024-08-20 04:47 UTC, merged